name: update
on:
  push:
    branches:
      - main
  schedule:
    - cron: "54 */4 * * *"
  workflow_dispatch:

env:
  domain: konspiratori.sk
  filename: konspiratori-sk-filter.txt
  sourceurl: https://konspiratori.sk/static/lists/zoznam.txt

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull list, update format and save
        run: |
          cat <<-EOF > $filename
          ! Homepage: https://${domain}
          ! Title: ${domain} filter list
          ! Last change: $(date)
          ! GitHub repository: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
          ! Note: This is an unofficial blocklist not related to the creators of ${domain}
          !
          $(curl -so - $sourceurl | awk -F ',' '{print "||"$1"^"}')
          EOF
      - name: verify basic format/content
        run: grep -qE "^\|\|(([a-zA-Z](-?[a-zA-Z0-9])*)\.)+[a-zA-Z]{2,}\^$" $filename || exit 1
      - name: Commit updated file
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add $filename
          git commit -am "Updated filter"
          git push
